def get_all_photovoltaic():
    data = {
        "pv_module": {
            "mono_si": {
                "mono_300Wp": {
                    "rated_power_wp": 300,
                    "open_circuit_voltage_v": 39.7,
                    "short_circuit_current_a": 9.85,
                    "vmpp_v": 32.6,
                    "impp_a": 9.20,
                    "efficiency_percent": 18.5,
                    "temp_coeff_power_percent_per_c": -0.38,
                    "dimensions_mm": "1580×808×35",
                    "weight_kg": 18.5,
                    "cell_type": "mono_si",
                    "standard": "GB/T 9535.1-2025 / IEC 61215",
                    "source_note": "组件参数依据GB/T 9535.1-2025、IEC 61215及主流厂家产品手册"
                },
                "mono_350Wp": {
                    "rated_power_wp": 350,
                    "open_circuit_voltage_v": 44.5,
                    "short_circuit_current_a": 10.05,
                    "vmpp_v": 36.8,
                    "impp_a": 9.51,
                    "efficiency_percent": 19.3,
                    "temp_coeff_power_percent_per_c": -0.37,
                    "dimensions_mm": "1650×992×35",
                    "weight_kg": 20.0,
                    "cell_type": "mono_si",
                    "standard": "GB/T 9535.1-2025 / IEC 61215",
                    "source_note": "组件参数依据GB/T 9535.1-2025、IEC 61215及主流厂家产品手册"
                },
                "mono_400Wp": {
                    "rated_power_wp": 400,
                    "open_circuit_voltage_v": 49.5,
                    "short_circuit_current_a": 10.35,
                    "vmpp_v": 41.0,
                    "impp_a": 9.76,
                    "efficiency_percent": 20.3,
                    "temp_coeff_power_percent_per_c": -0.37,
                    "dimensions_mm": "1722×1134×30",
                    "weight_kg": 21.5,
                    "cell_type": "mono_si",
                    "standard": "GB/T 9535.1-2025 / IEC 61215",
                    "source_note": "组件参数依据GB/T 9535.1-2025、IEC 61215及主流厂家产品手册"
                },
                "mono_450Wp": {
                    "rated_power_wp": 450,
                    "open_circuit_voltage_v": 52.3,
                    "short_circuit_current_a": 11.15,
                    "vmpp_v": 42.8,
                    "impp_a": 10.51,
                    "efficiency_percent": 20.8,
                    "temp_coeff_power_percent_per_c": -0.36,
                    "dimensions_mm": "1767×1134×30",
                    "weight_kg": 23.0,
                    "cell_type": "mono_si",
                    "standard": "GB/T 9535.1-2025 / IEC 61215",
                    "source_note": "组件参数依据GB/T 9535.1-2025、IEC 61215及主流厂家产品手册"
                },
                "mono_500Wp": {
                    "rated_power_wp": 500,
                    "open_circuit_voltage_v": 53.8,
                    "short_circuit_current_a": 12.05,
                    "vmpp_v": 44.2,
                    "impp_a": 11.31,
                    "efficiency_percent": 21.2,
                    "temp_coeff_power_percent_per_c": -0.36,
                    "dimensions_mm": "2094×1134×30",
                    "weight_kg": 26.5,
                    "cell_type": "mono_si",
                    "standard": "GB/T 9535.1-2025 / IEC 61215",
                    "source_note": "组件参数依据GB/T 9535.1-2025、IEC 61215及主流厂家产品手册"
                },
                "mono_550Wp": {
                    "rated_power_wp": 550,
                    "open_circuit_voltage_v": 55.5,
                    "short_circuit_current_a": 12.85,
                    "vmpp_v": 45.6,
                    "impp_a": 12.06,
                    "efficiency_percent": 21.5,
                    "temp_coeff_power_percent_per_c": -0.35,
                    "dimensions_mm": "2278×1134×30",
                    "weight_kg": 28.5,
                    "cell_type": "mono_si",
                    "standard": "GB/T 9535.1-2025 / IEC 61215",
                    "source_note": "组件参数依据GB/T 9535.1-2025、IEC 61215及主流厂家产品手册"
                },
                "mono_600Wp": {
                    "rated_power_wp": 600,
                    "open_circuit_voltage_v": 57.2,
                    "short_circuit_current_a": 13.60,
                    "vmpp_v": 47.0,
                    "impp_a": 12.77,
                    "efficiency_percent": 21.8,
                    "temp_coeff_power_percent_per_c": -0.35,
                    "dimensions_mm": "2278×1134×35",
                    "weight_kg": 30.0,
                    "cell_type": "mono_si",
                    "standard": "GB/T 9535.1-2025 / IEC 61215",
                    "source_note": "组件参数依据GB/T 9535.1-2025、IEC 61215及主流厂家产品手册"
                }
            },
            "poly_si": {
                "poly_250Wp": {
                    "rated_power_wp": 250,
                    "open_circuit_voltage_v": 37.8,
                    "short_circuit_current_a": 8.85,
                    "vmpp_v": 30.5,
                    "impp_a": 8.20,
                    "efficiency_percent": 15.4,
                    "temp_coeff_power_percent_per_c": -0.40,
                    "dimensions_mm": "1640×992×35",
                    "weight_kg": 18.0,
                    "cell_type": "poly_si",
                    "standard": "GB/T 9535.1-2025 / IEC 61215",
                    "source_note": "组件参数依据GB/T 9535.1-2025、IEC 61215及主流厂家产品手册"
                },
                "poly_270Wp": {
                    "rated_power_wp": 270,
                    "open_circuit_voltage_v": 39.2,
                    "short_circuit_current_a": 9.10,
                    "vmpp_v": 31.8,
                    "impp_a": 8.49,
                    "efficiency_percent": 16.0,
                    "temp_coeff_power_percent_per_c": -0.40,
                    "dimensions_mm": "1640×992×35",
                    "weight_kg": 18.5,
                    "cell_type": "poly_si",
                    "standard": "GB/T 9535.1-2025 / IEC 61215",
                    "source_note": "组件参数依据GB/T 9535.1-2025、IEC 61215及主流厂家产品手册"
                },
                "poly_300Wp": {
                    "rated_power_wp": 300,
                    "open_circuit_voltage_v": 41.5,
                    "short_circuit_current_a": 9.60,
                    "vmpp_v": 33.8,
                    "impp_a": 8.88,
                    "efficiency_percent": 16.8,
                    "temp_coeff_power_percent_per_c": -0.40,
                    "dimensions_mm": "1650×992×35",
                    "weight_kg": 19.0,
                    "cell_type": "poly_si",
                    "standard": "GB/T 9535.1-2025 / IEC 61215",
                    "source_note": "组件参数依据GB/T 9535.1-2025、IEC 61215及主流厂家产品手册"
                },
                "poly_330Wp": {
                    "rated_power_wp": 330,
                    "open_circuit_voltage_v": 45.8,
                    "short_circuit_current_a": 9.55,
                    "vmpp_v": 37.2,
                    "impp_a": 8.87,
                    "efficiency_percent": 17.0,
                    "temp_coeff_power_percent_per_c": -0.40,
                    "dimensions_mm": "1680×992×35",
                    "weight_kg": 19.5,
                    "cell_type": "poly_si",
                    "standard": "GB/T 9535.1-2025 / IEC 61215",
                    "source_note": "组件参数依据GB/T 9535.1-2025、IEC 61215及主流厂家产品手册"
                },
                "poly_350Wp": {
                    "rated_power_wp": 350,
                    "open_circuit_voltage_v": 46.8,
                    "short_circuit_current_a": 9.80,
                    "vmpp_v": 38.2,
                    "impp_a": 9.16,
                    "efficiency_percent": 17.3,
                    "temp_coeff_power_percent_per_c": -0.40,
                    "dimensions_mm": "1700×992×35",
                    "weight_kg": 20.0,
                    "cell_type": "poly_si",
                    "standard": "GB/T 9535.1-2025 / IEC 61215",
                    "source_note": "组件参数依据GB/T 9535.1-2025、IEC 61215及主流厂家产品手册"
                },
                "poly_370Wp": {
                    "rated_power_wp": 370,
                    "open_circuit_voltage_v": 47.5,
                    "short_circuit_current_a": 10.10,
                    "vmpp_v": 38.8,
                    "impp_a": 9.54,
                    "efficiency_percent": 17.5,
                    "temp_coeff_power_percent_per_c": -0.40,
                    "dimensions_mm": "1700×992×35",
                    "weight_kg": 20.5,
                    "cell_type": "poly_si",
                    "standard": "GB/T 9535.1-2025 / IEC 61215",
                    "source_note": "组件参数依据GB/T 9535.1-2025、IEC 61215及主流厂家产品手册"
                }
            },
            "thin_film": {
                "thin_250Wp": {
                    "rated_power_wp": 250,
                    "open_circuit_voltage_v": 165.0,
                    "short_circuit_current_a": 2.15,
                    "vmpp_v": 132.0,
                    "impp_a": 1.89,
                    "efficiency_percent": 12.5,
                    "temp_coeff_power_percent_per_c": -0.30,
                    "dimensions_mm": "1200×600×7",
                    "weight_kg": 12.0,
                    "cell_type": "thin_film",
                    "standard": "GB/T 9535.1-2025 / IEC 61215",
                    "source_note": "组件参数依据GB/T 9535.1-2025、IEC 61215及主流厂家产品手册"
                },
                "thin_280Wp": {
                    "rated_power_wp": 280,
                    "open_circuit_voltage_v": 172.0,
                    "short_circuit_current_a": 2.25,
                    "vmpp_v": 138.0,
                    "impp_a": 2.03,
                    "efficiency_percent": 12.8,
                    "temp_coeff_power_percent_per_c": -0.30,
                    "dimensions_mm": "1200×600×7",
                    "weight_kg": 12.0,
                    "cell_type": "thin_film",
                    "standard": "GB/T 9535.1-2025 / IEC 61215",
                    "source_note": "组件参数依据GB/T 9535.1-2025、IEC 61215及主流厂家产品手册"
                },
                "thin_310Wp": {
                    "rated_power_wp": 310,
                    "open_circuit_voltage_v": 178.0,
                    "short_circuit_current_a": 2.38,
                    "vmpp_v": 143.0,
                    "impp_a": 2.17,
                    "efficiency_percent": 13.1,
                    "temp_coeff_power_percent_per_c": -0.30,
                    "dimensions_mm": "1200×600×7",
                    "weight_kg": 12.5,
                    "cell_type": "thin_film",
                    "standard": "GB/T 9535.1-2025 / IEC 61215",
                    "source_note": "组件参数依据GB/T 9535.1-2025、IEC 61215及主流厂家产品手册"
                },
                "thin_340Wp": {
                    "rated_power_wp": 340,
                    "open_circuit_voltage_v": 185.0,
                    "short_circuit_current_a": 2.55,
                    "vmpp_v": 148.0,
                    "impp_a": 2.30,
                    "efficiency_percent": 13.5,
                    "temp_coeff_power_percent_per_c": -0.30,
                    "dimensions_mm": "1200×600×7",
                    "weight_kg": 12.5,
                    "cell_type": "thin_film",
                    "standard": "GB/T 9535.1-2025 / IEC 61215",
                    "source_note": "组件参数依据GB/T 9535.1-2025、IEC 61215及主流厂家产品手册"
                },
                "thin_360Wp": {
                    "rated_power_wp": 360,
                    "open_circuit_voltage_v": 190.0,
                    "short_circuit_current_a": 2.62,
                    "vmpp_v": 152.0,
                    "impp_a": 2.37,
                    "efficiency_percent": 13.8,
                    "temp_coeff_power_percent_per_c": -0.30,
                    "dimensions_mm": "1200×600×7",
                    "weight_kg": 13.0,
                    "cell_type": "thin_film",
                    "standard": "GB/T 9535.1-2025 / IEC 61215",
                    "source_note": "组件参数依据GB/T 9535.1-2025、IEC 61215及主流厂家产品手册"
                },
                "thin_380Wp": {
                    "rated_power_wp": 380,
                    "open_circuit_voltage_v": 196.0,
                    "short_circuit_current_a": 2.70,
                    "vmpp_v": 157.0,
                    "impp_a": 2.42,
                    "efficiency_percent": 14.0,
                    "temp_coeff_power_percent_per_c": -0.30,
                    "dimensions_mm": "1200×600×7",
                    "weight_kg": 13.0,
                    "cell_type": "thin_film",
                    "standard": "GB/T 9535.1-2025 / IEC 61215",
                    "source_note": "组件参数依据GB/T 9535.1-2025、IEC 61215及主流厂家产品手册"
                }
            }
        },
        "string_inverter": {
            "string_3kW": {
                "rated_power_kw": 3,
                "max_dc_power_kw": 3.9,
                "mppt_count": 1,
                "mppt_voltage_range_v": "100~500",
                "rated_ac_voltage_v": 380,
                "rated_frequency_hz": 50,
                "power_factor_range": "0.8leading~0.8lagging",
                "max_efficiency_percent": 97.5,
                "protection_functions": ["anti_islanding", "overvoltage", "undervoltage", "overfrequency", "underfrequency", "overcurrent"],
                "standard": "GB/T 19964-2012",
                "source_note": "参数依据GB/T 19964-2012及主流厂家产品手册"
            },
            "string_5kW": {
                "rated_power_kw": 5,
                "max_dc_power_kw": 6.5,
                "mppt_count": 1,
                "mppt_voltage_range_v": "120~550",
                "rated_ac_voltage_v": 380,
                "rated_frequency_hz": 50,
                "power_factor_range": "0.8leading~0.8lagging",
                "max_efficiency_percent": 97.8,
                "protection_functions": ["anti_islanding", "overvoltage", "undervoltage", "overfrequency", "underfrequency", "overcurrent"],
                "standard": "GB/T 19964-2012",
                "source_note": "参数依据GB/T 19964-2012及主流厂家产品手册"
            },
            "string_8kW": {
                "rated_power_kw": 8,
                "max_dc_power_kw": 10.4,
                "mppt_count": 2,
                "mppt_voltage_range_v": "160~600",
                "rated_ac_voltage_v": 380,
                "rated_frequency_hz": 50,
                "power_factor_range": "0.8leading~0.8lagging",
                "max_efficiency_percent": 98.0,
                "protection_functions": ["anti_islanding", "overvoltage", "undervoltage", "overfrequency", "underfrequency", "overcurrent"],
                "standard": "GB/T 19964-2012",
                "source_note": "参数依据GB/T 19964-2012及主流厂家产品手册"
            },
            "string_10kW": {
                "rated_power_kw": 10,
                "max_dc_power_kw": 13.0,
                "mppt_count": 2,
                "mppt_voltage_range_v": "160~600",
                "rated_ac_voltage_v": 380,
                "rated_frequency_hz": 50,
                "power_factor_range": "0.8leading~0.8lagging",
                "max_efficiency_percent": 98.0,
                "protection_functions": ["anti_islanding", "overvoltage", "undervoltage", "overfrequency", "underfrequency", "overcurrent"],
                "standard": "GB/T 19964-2012",
                "source_note": "参数依据GB/T 19964-2012及主流厂家产品手册"
            },
            "string_15kW": {
                "rated_power_kw": 15,
                "max_dc_power_kw": 19.5,
                "mppt_count": 2,
                "mppt_voltage_range_v": "200~800",
                "rated_ac_voltage_v": 380,
                "rated_frequency_hz": 50,
                "power_factor_range": "0.8leading~0.8lagging",
                "max_efficiency_percent": 98.2,
                "protection_functions": ["anti_islanding", "overvoltage", "undervoltage", "overfrequency", "underfrequency", "overcurrent"],
                "standard": "GB/T 19964-2012",
                "source_note": "参数依据GB/T 19964-2012及主流厂家产品手册"
            },
            "string_20kW": {
                "rated_power_kw": 20,
                "max_dc_power_kw": 26.0,
                "mppt_count": 2,
                "mppt_voltage_range_v": "200~800",
                "rated_ac_voltage_v": 380,
                "rated_frequency_hz": 50,
                "power_factor_range": "0.8leading~0.8lagging",
                "max_efficiency_percent": 98.3,
                "protection_functions": ["anti_islanding", "overvoltage", "undervoltage", "overfrequency", "underfrequency", "overcurrent"],
                "standard": "GB/T 19964-2012",
                "source_note": "参数依据GB/T 19964-2012及主流厂家产品手册"
            },
            "string_30kW": {
                "rated_power_kw": 30,
                "max_dc_power_kw": 39.0,
                "mppt_count": 2,
                "mppt_voltage_range_v": "200~1000",
                "rated_ac_voltage_v": 380,
                "rated_frequency_hz": 50,
                "power_factor_range": "0.8leading~0.8lagging",
                "max_efficiency_percent": 98.4,
                "protection_functions": ["anti_islanding", "overvoltage", "undervoltage", "overfrequency", "underfrequency", "overcurrent"],
                "standard": "GB/T 19964-2012",
                "source_note": "参数依据GB/T 19964-2012及主流厂家产品手册"
            },
            "string_50kW": {
                "rated_power_kw": 50,
                "max_dc_power_kw": 65.0,
                "mppt_count": 2,
                "mppt_voltage_range_v": "200~1000",
                "rated_ac_voltage_v": 380,
                "rated_frequency_hz": 50,
                "power_factor_range": "0.8leading~0.8lagging",
                "max_efficiency_percent": 98.5,
                "protection_functions": ["anti_islanding", "overvoltage", "undervoltage", "overfrequency", "underfrequency", "overcurrent"],
                "standard": "GB/T 19964-2012",
                "source_note": "参数依据GB/T 19964-2012及主流厂家产品手册"
            },
            "string_80kW": {
                "rated_power_kw": 80,
                "max_dc_power_kw": 104.0,
                "mppt_count": 3,
                "mppt_voltage_range_v": "200~1000",
                "rated_ac_voltage_v": 380,
                "rated_frequency_hz": 50,
                "power_factor_range": "0.8leading~0.8lagging",
                "max_efficiency_percent": 98.6,
                "protection_functions": ["anti_islanding", "overvoltage", "undervoltage", "overfrequency", "underfrequency", "overcurrent"],
                "standard": "GB/T 19964-2012",
                "source_note": "参数依据GB/T 19964-2012及主流厂家产品手册"
            },
            "string_100kW": {
                "rated_power_kw": 100,
                "max_dc_power_kw": 130.0,
                "mppt_count": 3,
                "mppt_voltage_range_v": "200~1000",
                "rated_ac_voltage_v": 380,
                "rated_frequency_hz": 50,
                "power_factor_range": "0.8leading~0.8lagging",
                "max_efficiency_percent": 98.7,
                "protection_functions": ["anti_islanding", "overvoltage", "undervoltage", "overfrequency", "underfrequency", "overcurrent"],
                "standard": "GB/T 19964-2012",
                "source_note": "参数依据GB/T 19964-2012及主流厂家产品手册"
            }
        },
        "central_inverter": {
            "central_100kW": {
                "rated_power_kw": 100,
                "max_dc_power_kw": 130.0,
                "mppt_count": 1,
                "mppt_voltage_range_v": "450~820",
                "rated_ac_voltage_v": 380,
                "rated_frequency_hz": 50,
                "power_factor_range": "0.8leading~0.8lagging",
                "max_efficiency_percent": 98.8,
                "protection_functions": ["anti_islanding", "overvoltage", "undervoltage", "overfrequency", "underfrequency", "overcurrent"],
                "standard": "GB/T 19964-2012",
                "source_note": "参数依据GB/T 19964-2012及主流厂家产品手册"
            },
            "central_250kW": {
                "rated_power_kw": 250,
                "max_dc_power_kw": 325.0,
                "mppt_count": 2,
                "mppt_voltage_range_v": "450~1000",
                "rated_ac_voltage_v": 380,
                "rated_frequency_hz": 50,
                "power_factor_range": "0.8leading~0.8lagging",
                "max_efficiency_percent": 98.9,
                "protection_functions": ["anti_islanding", "overvoltage", "undervoltage", "overfrequency", "underfrequency", "overcurrent"],
                "standard": "GB/T 19964-2012",
                "source_note": "参数依据GB/T 19964-2012及主流厂家产品手册"
            },
            "central_500kW": {
                "rated_power_kw": 500,
                "max_dc_power_kw": 650.0,
                "mppt_count": 2,
                "mppt_voltage_range_v": "450~1000",
                "rated_ac_voltage_v": 315,
                "rated_frequency_hz": 50,
                "power_factor_range": "0.8leading~0.8lagging",
                "max_efficiency_percent": 99.0,
                "protection_functions": ["anti_islanding", "overvoltage", "undervoltage", "overfrequency", "underfrequency", "overcurrent"],
                "voltage_note": "315V匹配升压变压器低压侧,需配10/0.315kV升压变接入配网",
                "standard": "GB/T 19964-2012",
                "source_note": "参数依据GB/T 19964-2012及主流厂家产品手册"
            },
            "central_630kW": {
                "rated_power_kw": 630,
                "max_dc_power_kw": 820.0,
                "mppt_count": 2,
                "mppt_voltage_range_v": "450~1000",
                "rated_ac_voltage_v": 315,
                "rated_frequency_hz": 50,
                "power_factor_range": "0.8leading~0.8lagging",
                "max_efficiency_percent": 99.0,
                "protection_functions": ["anti_islanding", "overvoltage", "undervoltage", "overfrequency", "underfrequency", "overcurrent"],
                "voltage_note": "315V匹配升压变压器低压侧,需配10/0.315kV升压变接入配网",
                "standard": "GB/T 19964-2012",
                "source_note": "参数依据GB/T 19964-2012及主流厂家产品手册"
            }
        }
    }
    return _enhance_photovoltaic(data)


def _enhance_photovoltaic(data):
    for category in ("string_inverter", "central_inverter"):
        for entry in data.get(category, {}).values():
            protections = entry.get("protection_functions", [])
            if isinstance(protections, (list, tuple, set)):
                entry.setdefault("anti_islanding", "anti_islanding" in protections)
            entry.setdefault("harmonic_current_limit_percent", 5)
    return data
