def _port(name, kind, voltage_levels, phase="ABC", direction="bidirectional"):
    return {
        "name": name,
        "kind": kind,
        "voltage_levels_kv": voltage_levels,
        "phase": phase,
        "direction": direction,
    }


def get_engineering_asset_schema():
    ac_lv_mv = [0.22, 0.38, 0.4, 10, 10.5, 35, 110]
    mv_levels = [10, 10.5, 35]
    lv_levels = [0.22, 0.38, 0.4]

    return {
        "metadata": {
            "name": "中国10kV-0.4kV配网规划系统工程对象模型",
            "version": "1.0.0",
            "purpose": "为图元库拖拽建模、参数录入、pandapower映射、规范校验和规划方案比较提供统一元数据。",
        },
        "base_system": {
            "frequency_hz": 50,
            "nominal_voltage_levels_kv": ac_lv_mv,
            "area_classes": ["A", "B", "C", "D", "E"],
            "operation_states": ["normal", "maintenance", "n_1", "fault", "islanded", "black_start"],
        },
        "classes": {
            "source_grid": {
                "display_name": "上级电网/外部电源",
                "palette_group": "电源",
                "pandapower_element": "ext_grid",
                "graphical": {"symbol": "source-grid", "icon_hint": "plug-zap", "min_size": [72, 48]},
                "ports": [_port("ac", "ac_terminal", mv_levels + [110])],
                "required_fields": ["vn_kv", "vm_pu", "s_sc_max_mva", "rx_max"],
                "optional_fields": ["s_sc_min_mva", "rx_min", "r0x0_max", "x0x_max", "controllable"],
                "calculations": ["power_flow", "short_circuit", "n_1", "opf"],
                "connection_rules": {"ac": ["busbar", "line_overhead", "line_cable", "switch_breaker"]},
            },
            "busbar": {
                "display_name": "母线/节点",
                "palette_group": "一次接线",
                "pandapower_element": "bus",
                "graphical": {"symbol": "busbar", "icon_hint": "minus", "min_size": [96, 28]},
                "ports": [_port("terminal", "ac_node", ac_lv_mv)],
                "required_fields": ["vn_kv", "name"],
                "optional_fields": ["min_vm_pu", "max_vm_pu", "zone", "area_class", "geodata"],
                "calculations": ["power_flow", "short_circuit", "state_estimation", "power_quality"],
                "connection_rules": {"terminal": ["source_grid", "transformer_2w", "transformer_3w", "line_overhead", "line_cable", "load", "sgen", "storage", "switch_breaker", "switch_disconnector"]},
            },
            "transformer_2w": {
                "display_name": "双绕组变压器",
                "palette_group": "变压器",
                "pandapower_element": "trafo",
                "graphical": {"symbol": "transformer-2w", "icon_hint": "circle-dot", "min_size": [80, 88]},
                "ports": [
                    _port("hv", "ac_terminal", [10, 10.5, 35, 110]),
                    _port("lv", "ac_terminal", [0.4, 10, 10.5, 35]),
                ],
                "required_fields": ["std_type", "sn_mva", "vn_hv_kv", "vn_lv_kv", "vk_percent", "vkr_percent", "pfe_kw", "i0_percent", "vector_group"],
                "optional_fields": [
                    "rated_current_hv_a", "rated_current_lv_a", "rated_current", "tap_side", "tap_min", "tap_max", "tap_step_percent", "tap_pos",
                    "cooling_type", "winding_type", "winding_material", "insulation_class",
                    "loss_level", "installation", "short_circuit_impedance_zero_sequence",
                    "thermal_model", "energy_efficiency", "design_life_years",
                    "dimensions_mm", "total_weight_kg", "oil_weight_kg", "cost_estimate_cny",
                ],
                "planning_fields": ["normal_loading_limit_percent", "economic_loading_range_percent", "n1_loading_limit_percent", "emergency_loading_limit_percent", "loading_limits", "loss_cost_cny_per_year", "spare_policy"],
                "calculations": ["power_flow", "short_circuit", "n_1", "opf", "loss_evaluation"],
                "connection_rules": {"hv": ["busbar", "switch_breaker", "line_cable", "line_overhead"], "lv": ["busbar", "switch_breaker", "line_cable", "line_overhead", "load", "sgen", "storage"]},
            },
            "transformer_3w": {
                "display_name": "三绕组主变",
                "palette_group": "变压器",
                "pandapower_element": "trafo3w",
                "graphical": {"symbol": "transformer-3w", "icon_hint": "circle-dot-dashed", "min_size": [96, 96]},
                "ports": [
                    _port("hv", "ac_terminal", [110]),
                    _port("mv", "ac_terminal", [35, 38.5]),
                    _port("lv", "ac_terminal", [10, 10.5, 11]),
                ],
                "required_fields": ["std_type", "sn_hv_mva", "sn_mv_mva", "sn_lv_mva", "vn_hv_kv", "vn_mv_kv", "vn_lv_kv", "vector_group"],
                "optional_fields": ["tap_side", "tap_min", "tap_max", "tap_step_percent", "pfe_kw", "i0_percent", "cost_estimate_cny"],
                "planning_fields": ["normal_loading_limit_percent", "emergency_loading_limit_percent", "parallel_operation_group"],
                "calculations": ["power_flow", "short_circuit", "n_1", "opf"],
                "connection_rules": {"hv": ["busbar", "switch_breaker"], "mv": ["busbar", "switch_breaker"], "lv": ["busbar", "switch_breaker"]},
            },
            "line_cable": {
                "display_name": "电力电缆",
                "palette_group": "线路",
                "pandapower_element": "line",
                "graphical": {"symbol": "cable", "icon_hint": "route", "min_size": [120, 24]},
                "ports": [_port("from", "ac_terminal", ac_lv_mv), _port("to", "ac_terminal", ac_lv_mv)],
                "required_fields": ["std_type", "length_km", "r_ohm_per_km", "x_ohm_per_km", "c_nf_per_km", "max_i_ka"],
                "optional_fields": [
                    "r0_ohm_per_km", "x0_ohm_per_km", "c0_nf_per_km", "conductor_material",
                    "cross_section_mm2", "insulation_type", "armor_type", "laying_method",
                    "soil_thermal_resistivity", "ambient_temperature_c", "parallel", "df",
                    "ampacity_reference", "derating_factors", "thermal_limits", "lifecycle",
                    "short_circuit_current_1s_ka", "short_circuit_i2t_ka2s", "short_circuit_rating", "endtemp_degree", "cost_cny_per_km",
                ],
                "planning_fields": ["corridor_id", "route_length_km", "max_voltage_drop_percent", "thermal_margin_percent", "civil_work_cost_cny_per_km"],
                "calculations": ["power_flow", "short_circuit", "n_1", "voltage_drop", "ampacity", "loss_evaluation"],
                "connection_rules": {"from": ["busbar", "switch_breaker", "switch_disconnector"], "to": ["busbar", "switch_breaker", "switch_disconnector", "ring_main_unit"]},
            },
            "line_overhead": {
                "display_name": "架空线路",
                "palette_group": "线路",
                "pandapower_element": "line",
                "graphical": {"symbol": "overhead-line", "icon_hint": "utility-pole", "min_size": [120, 24]},
                "ports": [_port("from", "ac_terminal", ac_lv_mv), _port("to", "ac_terminal", ac_lv_mv)],
                "required_fields": ["std_type", "length_km", "r_ohm_per_km", "x_ohm_per_km", "c_nf_per_km", "max_i_ka"],
                "optional_fields": ["conductor_material", "cross_section_mm2", "pole_type", "span_m", "ice_thickness_mm", "wind_pressure_pa", "ampacity_reference", "dynamic_line_rating", "mechanical_limits", "lifecycle", "r0_ohm_per_km", "x0_ohm_per_km", "cost_cny_per_km"],
                "planning_fields": ["right_of_way", "tree_clearance_m", "lightning_trip_rate_per_100km_year", "route_difficulty"],
                "calculations": ["power_flow", "short_circuit", "n_1", "voltage_drop", "ampacity", "reliability"],
                "connection_rules": {"from": ["busbar", "switch_breaker", "recloser"], "to": ["busbar", "switch_breaker", "recloser", "sectionalizer"]},
            },
            "switch_breaker": {
                "display_name": "断路器",
                "palette_group": "开关保护",
                "pandapower_element": "switch",
                "graphical": {"symbol": "breaker", "icon_hint": "toggle-right", "min_size": [56, 36]},
                "ports": [_port("terminal", "ac_terminal", ac_lv_mv)],
                "required_fields": ["rated_voltage_kv", "rated_current_a", "rated_short_circuit_breaking_current_ka"],
                "optional_fields": ["mechanical_life_count", "operating_sequence", "short_time_withstand", "rated_short_time_duration_s", "temperature_rise_limit_c", "endurance", "internal_arc_class", "protection_functions", "remote_control", "in_ka"],
                "planning_fields": ["automation_level", "fault_isolation_time_s", "cost_estimate_cny"],
                "calculations": ["topology_switching", "short_circuit_check", "n_1", "reliability"],
                "connection_rules": {"terminal": ["busbar", "line_cable", "line_overhead", "transformer_2w", "transformer_3w"]},
            },
            "switch_disconnector": {
                "display_name": "隔离/负荷开关",
                "palette_group": "开关保护",
                "pandapower_element": "switch",
                "graphical": {"symbol": "disconnector", "icon_hint": "split", "min_size": [56, 36]},
                "ports": [_port("terminal", "ac_terminal", ac_lv_mv)],
                "required_fields": ["rated_voltage_kv", "rated_current_a", "switch_type"],
                "optional_fields": ["short_time_withstand_current_ka", "remote_control", "motorized", "visible_break"],
                "planning_fields": ["sectionalizing_role", "normal_open", "operation_policy"],
                "calculations": ["topology_switching", "n_1", "reliability"],
                "connection_rules": {"terminal": ["busbar", "line_cable", "line_overhead", "ring_main_unit"]},
            },
            "fuse": {
                "display_name": "熔断器",
                "palette_group": "开关保护",
                "pandapower_element": "fuse",
                "graphical": {"symbol": "fuse", "icon_hint": "badge-alert", "min_size": [56, 36]},
                "ports": [_port("terminal", "ac_terminal", mv_levels)],
                "required_fields": ["i_rated_a", "rated_voltage_kv", "rated_breaking_current_ka"],
                "optional_fields": ["time_current_curve", "time_current_curve_data", "fuse_element_current_series", "minimum_melting_current_a", "selection_guide", "coordination_margin_s"],
                "planning_fields": ["protection_zone", "backup_protection"],
                "calculations": ["protection_coordination", "short_circuit_check"],
                "connection_rules": {"terminal": ["line_overhead", "transformer_2w", "ring_main_unit"]},
            },
            "ring_main_unit": {
                "display_name": "环网柜/RMU",
                "palette_group": "成套设备",
                "pandapower_element": "group",
                "graphical": {"symbol": "ring-main-unit", "icon_hint": "box", "min_size": [112, 72]},
                "ports": [_port("in", "ac_terminal", mv_levels), _port("out", "ac_terminal", mv_levels), _port("trafo", "ac_terminal", mv_levels)],
                "required_fields": ["rated_voltage_kv", "rated_current_a", "unit_scheme", "feeder_count"],
                "optional_fields": ["gas_insulation", "automation_terminal", "fault_indicator", "protection_functions"],
                "planning_fields": ["ring_section_id", "normal_open_switch", "automation_level", "cost_estimate_cny"],
                "calculations": ["topology_switching", "n_1", "reliability"],
                "connection_rules": {"in": ["line_cable"], "out": ["line_cable"], "trafo": ["transformer_2w", "switch_breaker", "fuse"]},
            },
            "box_substation": {
                "display_name": "箱式变电站/台区",
                "palette_group": "成套设备",
                "pandapower_element": "group",
                "graphical": {"symbol": "box-substation", "icon_hint": "warehouse", "min_size": [120, 88]},
                "ports": [_port("hv", "ac_terminal", [10, 10.5]), _port("lv", "ac_terminal", lv_levels)],
                "required_fields": ["std_type", "sn_kva", "hv_feeder_count", "lv_feeder_count"],
                "optional_fields": ["enclosure_class", "transformer_std_type", "switchgear_scheme", "metering_scheme"],
                "planning_fields": ["service_radius_m", "household_count", "load_density_kw_per_km2", "cost_estimate_cny"],
                "calculations": ["power_flow", "short_circuit", "load_forecast", "planning_comparison"],
                "connection_rules": {"hv": ["line_cable", "line_overhead", "ring_main_unit"], "lv": ["line_cable", "line_overhead", "load", "ev_charger", "pv_inverter"]},
            },
            "load": {
                "display_name": "负荷",
                "palette_group": "负荷",
                "pandapower_element": "load",
                "graphical": {"symbol": "load", "icon_hint": "factory", "min_size": [72, 52]},
                "ports": [_port("ac", "ac_terminal", ac_lv_mv)],
                "required_fields": ["p_mw", "q_mvar", "load_type"],
                "optional_fields": ["cos_phi", "annual_energy_mwh", "profile_id", "voltage_dependency", "criticality_level"],
                "planning_fields": ["growth_rate_percent_per_year", "simultaneity_factor", "demand_response_capable"],
                "calculations": ["power_flow", "load_forecast", "reliability_impact", "planning_comparison"],
                "connection_rules": {"ac": ["busbar", "line_cable", "line_overhead", "box_substation"]},
            },
            "pv_array": {
                "display_name": "光伏组件阵列",
                "palette_group": "新能源",
                "pandapower_element": "sgen",
                "graphical": {"symbol": "pv-array", "icon_hint": "solar-panel", "min_size": [88, 60]},
                "ports": [_port("dc", "dc_terminal", [], phase="DC")],
                "required_fields": ["module_type", "module_count", "dc_capacity_kwp", "tilt_degree", "azimuth_degree"],
                "optional_fields": ["string_count", "modules_per_string", "temperature_model", "degradation_percent_per_year"],
                "planning_fields": ["generation_profile_id", "curtailment_allowed", "land_or_roof_area_m2"],
                "calculations": ["pv_yield", "hosting_capacity", "power_quality"],
                "connection_rules": {"dc": ["pv_inverter"]},
            },
            "pv_inverter": {
                "display_name": "光伏逆变器",
                "palette_group": "新能源",
                "pandapower_element": "sgen",
                "graphical": {"symbol": "pv-inverter", "icon_hint": "sun", "min_size": [88, 60]},
                "ports": [_port("dc", "dc_terminal", [], phase="DC"), _port("ac", "ac_terminal", [0.4, 10, 35])],
                "required_fields": ["rated_power_kw", "sn_mva", "rated_ac_voltage_v", "power_factor_range"],
                "optional_fields": ["mppt_count", "max_dc_power_kw", "q_capability_curve", "anti_islanding", "low_voltage_ride_through"],
                "planning_fields": ["hosting_capacity_limit", "volt_var_enabled", "curtailment_priority"],
                "calculations": ["power_flow", "opf", "hosting_capacity", "voltage_rise", "power_quality"],
                "connection_rules": {"dc": ["pv_array"], "ac": ["busbar", "line_cable", "box_substation"]},
            },
            "wind_turbine": {
                "display_name": "分布式风机",
                "palette_group": "新能源",
                "pandapower_element": "sgen",
                "graphical": {"symbol": "wind-turbine", "icon_hint": "wind", "min_size": [88, 72]},
                "ports": [_port("ac", "ac_terminal", [0.4, 10, 35])],
                "required_fields": ["rated_power_kw", "rated_voltage_v", "cut_in_speed_m_s", "rated_wind_speed_m_s"],
                "optional_fields": ["power_curve", "reactive_control_mode", "fault_ride_through"],
                "planning_fields": ["wind_profile_id", "capacity_factor_percent", "curtailment_allowed"],
                "calculations": ["power_flow", "opf", "hosting_capacity", "power_quality"],
                "connection_rules": {"ac": ["busbar", "line_cable", "line_overhead"]},
            },
            "storage": {
                "display_name": "电化学储能",
                "palette_group": "新能源",
                "pandapower_element": "storage",
                "graphical": {"symbol": "battery-storage", "icon_hint": "battery-charging", "min_size": [88, 60]},
                "ports": [_port("ac", "ac_terminal", [0.4, 10, 35])],
                "required_fields": ["p_mw", "max_e_mwh", "soc_percent", "sn_mva"],
                "optional_fields": ["min_e_mwh", "round_trip_efficiency_percent", "cycle_life_count", "pcs_type", "battery_type"],
                "planning_fields": ["dispatch_strategy", "peak_shaving_target_kw", "backup_duration_h", "revenue_streams"],
                "calculations": ["power_flow", "opf", "time_series", "resilience", "planning_comparison"],
                "connection_rules": {"ac": ["busbar", "line_cable", "box_substation"]},
            },
            "ev_charger": {
                "display_name": "充电桩/充电站",
                "palette_group": "新能源负荷",
                "pandapower_element": "load",
                "graphical": {"symbol": "ev-charger", "icon_hint": "battery-charging", "min_size": [80, 56]},
                "ports": [_port("ac", "ac_terminal", lv_levels + [10])],
                "required_fields": ["rated_power_kw", "charger_type", "connector_count", "power_factor"],
                "optional_fields": ["charging_profile_id", "simultaneity_factor", "harmonic_current_percent", "v2g_capable"],
                "planning_fields": ["evening_peak_factor", "managed_charging", "station_queue_model"],
                "calculations": ["power_flow", "load_forecast", "power_quality", "planning_comparison"],
                "connection_rules": {"ac": ["busbar", "line_cable", "box_substation"]},
            },
            "reactive_compensation": {
                "display_name": "无功补偿/电容电抗",
                "palette_group": "无功与电能质量",
                "pandapower_element": "shunt",
                "graphical": {"symbol": "capacitor-bank", "icon_hint": "badge-plus", "min_size": [80, 52]},
                "ports": [_port("ac", "ac_terminal", ac_lv_mv)],
                "required_fields": ["q_mvar", "vn_kv", "step_count"],
                "optional_fields": ["detuning_reactor_percent", "switching_mode", "controller_type", "harmonic_filter_order"],
                "planning_fields": ["target_power_factor", "voltage_control_band_pu", "switching_times_limit_per_day"],
                "calculations": ["power_flow", "opf", "voltage_control", "power_quality"],
                "connection_rules": {"ac": ["busbar"]},
            },
            "metering_ct_pt": {
                "display_name": "计量/互感器",
                "palette_group": "计量监测",
                "pandapower_element": "measurement",
                "graphical": {"symbol": "metering", "icon_hint": "gauge", "min_size": [72, 48]},
                "ports": [_port("sense", "measurement_terminal", ac_lv_mv)],
                "required_fields": ["device_type", "ratio", "accuracy_class"],
                "optional_fields": ["burden_va", "protection_class", "metering_class", "communication_protocol"],
                "planning_fields": ["measurement_point_role", "state_estimation_weight"],
                "calculations": ["state_estimation", "power_quality", "operation_monitoring"],
                "connection_rules": {"sense": ["busbar", "line_cable", "line_overhead", "transformer_2w"]},
            },
            "surge_arrester": {
                "display_name": "避雷器",
                "palette_group": "防雷接地",
                "pandapower_element": "auxiliary_asset",
                "graphical": {"symbol": "surge-arrester", "icon_hint": "shield-zap", "min_size": [64, 48]},
                "ports": [_port("protected", "ac_terminal", ac_lv_mv)],
                "required_fields": ["rated_voltage_kv", "continuous_operating_voltage_kv", "nominal_discharge_current_ka"],
                "optional_fields": ["residual_voltage_kv", "creepage_distance_mm", "pollution_level"],
                "planning_fields": ["protected_equipment_id", "lightning_zone", "maintenance_interval_year"],
                "calculations": ["insulation_coordination", "reliability"],
                "connection_rules": {"protected": ["busbar", "line_overhead", "transformer_2w", "switch_breaker"]},
            },
        },
    }
