from functools import lru_cache


def _check(rule_id, name, required_equipment_fields, required_result_fields, criterion, standard, severity="error"):
    return {
        "rule_id": rule_id,
        "name": name,
        "required_equipment_fields": required_equipment_fields,
        "required_result_fields": required_result_fields,
        "criterion": criterion,
        "standard": standard,
        "severity": severity,
    }


@lru_cache(maxsize=1)
def get_compliance_constraint_library():
    return {
        "metadata": {
            "name": "中国配网一次设备合规约束库",
            "version": "1.0.0",
            "purpose": "pandapower负责计算潮流、短路、时序和优化结果，本库负责按设备类型判定一次设备是否满足国标/行标/工程约束。",
            "standard_reference_basis": [
                {"code": "GB/T 15544.1-2023", "name": "三相交流系统短路电流计算 第1部分：电流计算", "use": "短路电流计算结果口径"},
                {"code": "GB/T 1984-2024", "name": "高压交流断路器", "use": "中压断路器开断、关合和额定值"},
                {"code": "GB/T 11022-2020", "name": "高压开关设备和控制设备标准的共用技术要求", "use": "高压开关设备通用额定值、短时耐受和温升"},
                {"code": "GB/T 3906-2020", "name": "3.6kV~40.5kV交流金属封闭开关设备和控制设备", "use": "10kV开关柜成套设备"},
                {"code": "GB/T 6451-2023", "name": "油浸式电力变压器技术参数和要求", "use": "油浸式变压器参数与温升"},
                {"code": "GB/T 10228-2023", "name": "干式电力变压器技术参数和要求", "use": "干式变压器参数与温升"},
                {"code": "GB/T 1094.3-2017", "name": "电力变压器 第3部分：绝缘水平、绝缘试验和外绝缘空气间隙", "use": "变压器绝缘水平"},
                {"code": "GB/T 1094.5-2008", "name": "电力变压器 第5部分：承受短路的能力", "use": "变压器短路承受能力"},
                {"code": "GB/T 17467-2020", "name": "高压/低压预装式变电站", "use": "箱式变电站成套要求"},
                {"code": "GB/T 12706.1~3-2020", "name": "额定电压1kV到35kV挤包绝缘电力电缆及附件", "use": "低压、中压电缆参数、试验和热稳定"},
                {"code": "GB/T 15166.2-2023", "name": "高压交流熔断器 第2部分：限流熔断器", "use": "高压熔断器开断能力和时间-电流特性"},
                {"code": "GB/T 15166.6-2023", "name": "高压交流熔断器 第6部分：用于变压器回路的熔断件选用导则", "use": "配变熔断件选择"},
                {"code": "GB/T 14048.2-2020", "name": "低压开关设备和控制设备 第2部分：断路器", "use": "低压ACB/MCCB分断能力和额定值"},
                {"code": "GB/T 20840.2-2014", "name": "互感器 第2部分：电流互感器的补充技术要求", "use": "CT热稳定、动稳定和准确级"},
                {"code": "GB/T 20840.3-2013", "name": "互感器 第3部分：电磁式电压互感器的补充技术要求", "use": "PT二次负荷和准确级"},
                {"code": "GB/T 36276-2023", "name": "电力储能用锂离子电池", "use": "储能电池SOC范围和安全性能"},
                {"code": "GB 50054-2023", "name": "低压配电设计规范", "use": "低压配电设计和电气火灾防护"},
                {"code": "GB 50052-2023", "name": "供配电系统设计规范", "use": "供配电系统设计原则"},
            ],
            "calculation_boundary": {
                "pandapower_outputs": [
                    "bus voltage vm_pu",
                    "line/trafo loading_percent",
                    "short-circuit ikss_ka, ip_ka, ith_ka",
                    "branch current/loading",
                    "sgen/storage/load p_mw and q_mvar",
                ],
                "library_checks": [
                    "额定电压",
                    "持续载流",
                    "短路开断",
                    "短时耐受",
                    "峰值耐受/关合",
                    "热稳定",
                    "绝缘与避雷配合",
                    "保护灵敏度与配合",
                    "新能源接入和电能质量约束",
                ],
            },
        },
        "pandapower_result_fields": {
            "power_flow": {
                "bus": ["vm_pu", "va_degree"],
                "line": ["loading_percent", "i_ka", "p_from_mw", "q_from_mvar", "pl_mw"],
                "trafo": ["loading_percent", "i_hv_ka", "i_lv_ka", "p_hv_mw", "q_hv_mvar", "pl_mw"],
                "trafo3w": ["loading_percent", "p_hv_mw", "p_mv_mw", "p_lv_mw", "pl_mw"],
                "load": ["p_mw", "q_mvar"],
                "sgen": ["p_mw", "q_mvar"],
                "storage": ["p_mw", "q_mvar"],
            },
            "short_circuit": {
                "bus": ["ikss_ka", "skss_mw", "ip_ka", "ith_ka"],
                "line": ["ikss_ka", "ip_ka", "ith_ka"],
                "trafo": ["ikss_hv_ka", "ikss_lv_ka", "ip_hv_ka", "ip_lv_ka", "ith_hv_ka", "ith_lv_ka"],
                "switchgear": ["ikss_ka", "ip_ka", "ith_ka"],
            },
        },
        "global_margins": {
            "rated_voltage_margin_percent": 0,
            "continuous_current_margin_percent": 0,
            "short_circuit_breaking_margin_percent": 0,
            "short_time_withstand_margin_percent": 0,
            "peak_withstand_margin_percent": 0,
            "planning_loading_margin_percent": 15,
        },
        "constraints_by_equipment_type": {
            "source_grid": [
                _check("SRC_SC_001", "上级电网最大/最小短路容量完整性", ["s_sc_max_mva", "s_sc_min_mva", "rx_max", "rx_min"], [], "短路计算前必须录入上级电网最大、最小短路容量和R/X比。", "GB/T 15544.1-2023"),
                _check("SRC_V_001", "电源电压设定范围", ["vn_kv", "vm_pu"], [], "vm_pu应处于规划或运行允许电压范围内。", "GB/T 12325-2023"),
            ],
            "busbar": [
                _check("BUS_V_001", "母线运行电压偏差", ["vn_kv"], ["vm_pu"], "母线vm_pu应满足对应电压等级允许范围。", "GB/T 12325-2023"),
                _check("BUS_SC_001", "母线短路电流水平记录", ["vn_kv"], ["ikss_ka", "ip_ka", "ith_ka"], "母线短路电流作为下游开关、母排、互感器、箱变校验输入。", "GB/T 15544.1-2023", "warning"),
            ],
            "transformer_2w": [
                _check("TR2_LOAD_001", "双绕组变压器正常负载率", ["sn_mva"], ["loading_percent"], "正常运行负载率不应超过工程参数库设定的normal_loading_limit_percent。", "GB 50052-2023"),
                _check("TR2_SC_PARAM_001", "双绕组变压器短路参数完整性", ["vk_percent", "vkr_percent", "vk0_percent", "vkr0_percent"], [], "三相和接地短路计算应具备正序及零序阻抗参数。", "GB/T 15544.1-2023"),
                _check("TR2_THERMAL_001", "变压器短时热稳定校核", ["short_time_thermal_current_ka", "short_time_duration_s"], ["ith_ka"], "ith_ka不得超过变压器短时热稳定电流。", "GB/T 1094.5-2008 / GB/T 6451-2023 / GB/T 10228-2023"),
                _check("TR2_INS_001", "变压器绝缘水平校核", ["rated_voltage_kv", "power_frequency_withstand_kv", "lightning_impulse_withstand_kv"], [], "绝缘水平应不低于设备最高电压对应要求。", "GB/T 1094.3-2017"),
                _check("TR2_TEMP_001", "变压器温升/温控保护", ["cooling_type", "insulation_class"], ["loading_percent"], "长期负载、冷却方式和温度保护定值应匹配。", "GB/T 6451-2023 / GB/T 10228-2023"),
            ],
            "transformer_3w": [
                _check("TR3_LOAD_001", "三绕组变压器负载率", ["sn_hv_mva", "sn_mv_mva", "sn_lv_mva"], ["loading_percent"], "各侧绕组负载率不应超过规划约束。", "GB 50052-2023"),
                _check("TR3_SC_PARAM_001", "三绕组短路阻抗完整性", ["vk_hv_percent", "vk_mv_percent", "vk_lv_percent", "vkr_hv_percent", "vkr_mv_percent", "vkr_lv_percent"], [], "三绕组短路计算前应具备各绕组短路阻抗。", "GB/T 15544.1-2023"),
            ],
            "box_substation": [
                _check("BOX_LOAD_001", "箱变容量校核", ["sn_mva"], ["loading_percent"], "箱变内变压器和低压出线负载率均应满足规划限值。", "GB/T 17467-2020"),
                _check("BOX_SC_001", "箱变成套短路耐受", ["rated_short_time_withstand_ka", "rated_peak_withstand_ka"], ["ith_ka", "ip_ka"], "箱变高低压成套设备短时和峰值耐受不应低于安装点短路水平。", "GB/T 17467-2020"),
                _check("BOX_IP_001", "箱变外壳防护等级", ["protection_class", "installation_environment"], [], "户外或污染环境下防护等级应满足安装环境要求。", "GB/T 17467-2020", "warning"),
            ],
            "line_cable": [
                _check("CAB_LOAD_001", "电缆持续载流量", ["max_i_ka"], ["i_ka"], "运行电流不得超过敷设方式修正后的允许载流量。", "GB/T 12706.1~3-2020"),
                _check("CAB_THERMAL_001", "电缆短路热稳定", ["short_circuit_current_1s_ka"], ["ith_ka"], "按I²t折算后，短路热效应不得超过电缆热稳定能力。", "GB/T 12706.1~3-2020"),
                _check("CAB_VDROP_001", "电缆压降", ["r_ohm_per_km", "x_ohm_per_km", "length_km"], ["voltage_drop_percent"], "线路末端压降应满足电压质量和规划目标。", "GB 50054-2023 / GB 50052-2023"),
                _check("CAB_ZERO_001", "电缆零序参数完整性", ["r0_ohm_per_km", "x0_ohm_per_km", "c0_nf_per_km"], [], "接地短路计算应具备零序参数。", "GB/T 15544.1-2023", "warning"),
            ],
            "line_overhead": [
                _check("OHL_LOAD_001", "架空线路持续载流量", ["max_i_ka"], ["i_ka"], "运行电流不得超过环境修正后的允许载流量。", "GB/T 1179-2017"),
                _check("OHL_THERMAL_001", "架空导线热稳定", ["short_circuit_current_1s_ka"], ["ith_ka"], "导线短路热稳定应满足故障切除时间。", "GB/T 1179-2017"),
                _check("OHL_VDROP_001", "架空线路压降", ["r_ohm_per_km", "x_ohm_per_km", "length_km"], ["voltage_drop_percent"], "末端压降应满足电压质量和规划目标。", "GB 50052-2023"),
                _check("OHL_MECH_001", "架空线路机械条件", ["span_m", "ice_thickness_mm", "wind_pressure_pa"], [], "杆塔、档距、覆冰、风压应满足线路机械设计条件。", "GB 50061-2010", "warning"),
            ],
            "switchgear_cabinet": [
                _check("SWG_V_001", "开关柜额定电压", ["rated_voltage_kv"], ["operating_voltage_kv"], "运行电压不得超过设备额定电压。", "GB/T 3906-2020 / GB/T 11022-2020"),
                _check("SWG_I_001", "开关柜额定电流", ["rated_current_a"], ["max_current_a"], "最大工作电流不得超过开关柜额定电流。", "GB/T 3906-2020 / GB/T 11022-2020"),
                _check("SWG_BREAK_001", "开关柜短路开断能力", ["rated_short_circuit_breaking_ka"], ["ikss_ka"], "安装点最大三相短路电流不得超过额定短路开断电流。", "GB/T 1984-2024"),
                _check("SWG_MAKE_001", "开关柜短路关合/峰值耐受", ["rated_short_circuit_making_ka"], ["ip_ka"], "短路峰值电流不得超过额定短路关合或峰值耐受电流。", "GB/T 3906-2020 / GB/T 11022-2020"),
                _check("SWG_THERMAL_001", "开关柜短时耐受", ["rated_short_time_withstand_ka_4s"], ["ith_ka"], "短时热电流不得超过额定短时耐受电流，需按持续时间折算。", "GB/T 3906-2020 / GB/T 11022-2020"),
            ],
            "switch_breaker": [
                _check("CB_I_001", "断路器额定电流", ["rated_current_a"], ["max_current_a"], "最大工作电流不得超过额定电流。", "GB/T 1984-2024"),
                _check("CB_BREAK_001", "断路器短路开断", ["rated_short_circuit_breaking_ka"], ["ikss_ka"], "最大短路电流不得超过额定短路开断电流。", "GB/T 1984-2024"),
                _check("CB_MAKE_001", "断路器短路关合", ["rated_short_circuit_making_ka"], ["ip_ka"], "短路峰值电流不得超过额定关合电流。", "GB/T 1984-2024"),
                _check("CB_THERMAL_001", "断路器短时耐受", ["rated_short_time_withstand_ka_4s"], ["ith_ka"], "短时热电流不得超过额定短时耐受电流。", "GB/T 1984-2024 / GB/T 11022-2020"),
            ],
            "load_switch": [
                _check("LS_I_001", "负荷开关额定电流", ["rated_current_a"], ["max_current_a"], "最大工作电流不得超过额定电流。", "GB/T 3804-2017"),
                _check("LS_MAKE_001", "负荷开关关合能力", ["rated_short_circuit_making_ka"], ["ip_ka"], "短路峰值电流不得超过额定短路关合电流。", "GB/T 3804-2017"),
                _check("LS_THERMAL_001", "负荷开关短时耐受", ["rated_short_time_withstand_ka_4s"], ["ith_ka"], "短时热电流不得超过额定短时耐受电流。", "GB/T 3804-2017 / GB/T 11022-2020"),
            ],
            "fuse": [
                _check("FUSE_BREAK_001", "熔断器开断能力", ["rated_breaking_current_ka"], ["ikss_ka"], "安装点最大预期短路电流不得超过熔断器额定开断电流。", "GB/T 15166.2-2023"),
                _check("FUSE_SELECT_001", "熔体额定电流选择", ["i_rated_a", "protected_equipment_rated_current_a"], ["max_current_a"], "熔体额定电流应躲过最大负荷和励磁涌流，并满足下级选择性。", "GB/T 15166.6-2023"),
                _check("FUSE_SENS_001", "熔断器保护灵敏度", ["time_current_curve_data"], ["min_fault_current_a"], "最小故障电流下应在允许时间内可靠熔断。", "DL/T 584-2021"),
            ],
            "recloser": [
                _check("REC_BREAK_001", "重合器开断能力", ["rated_short_circuit_breaking_ka"], ["ikss_ka"], "最大短路电流不得超过重合器额定开断能力。", "GB/T 25289-2010"),
                _check("REC_SEQ_001", "重合闸序列", ["reclose_sequence"], [], "架空线路可配置重合闸；纯电缆线路一般不宜投入自动重合。", "DL/T 584-2021", "warning"),
            ],
            "sectionalizer": [
                _check("SEC_MAKE_001", "分段器关合能力", ["rated_short_circuit_making_ka"], ["ip_ka"], "短路峰值电流不得超过额定关合能力。", "GB/T 25289-2010"),
                _check("SEC_COORD_001", "分段器与上级重合器配合", ["counting_times"], [], "计数次数和动作逻辑应与上级重合器时序配合。", "DL/T 584-2021"),
            ],
            "circuit_breaker_lv": [
                _check("LVCB_I_001", "低压断路器额定电流", ["rated_current_a"], ["max_current_a"], "最大工作电流不得超过整定或额定电流。", "GB/T 14048.2-2020 / GB 50054-2023"),
                _check("LVCB_BREAK_001", "低压断路器分断能力", ["breaking_capacity_ka"], ["ikss_ka"], "安装点最大短路电流不得超过分断能力。", "GB/T 14048.2-2020"),
                _check("LVCB_SELECT_001", "低压保护选择性", ["trip_type", "time_current_curve_data"], ["min_fault_current_a"], "上下级低压保护应具备选择性和灵敏度。", "GB 50054-2023", "warning"),
            ],
            "ring_main_unit": [
                _check("RMU_I_001", "环网柜额定电流", ["rated_current_a"], ["max_current_a"], "最大工作电流不得超过额定电流。", "GB/T 3906-2020 / GB/T 11022-2020"),
                _check("RMU_SC_001", "环网柜短路耐受/开断", ["rated_short_circuit_breaking_ka", "rated_short_time_withstand_ka_4s"], ["ikss_ka", "ith_ka"], "环网柜回路开断能力和短时耐受应不低于安装点短路水平。", "GB/T 3906-2020 / GB/T 11022-2020"),
            ],
            "reactive_compensation": [
                _check("RC_V_001", "无功补偿额定电压", ["rated_voltage_kv"], ["operating_voltage_kv"], "运行电压不得超过电容器或SVG允许电压。", "GB/T 11024-2019 / GB/T 12747.1-2017"),
                _check("RC_Q_001", "无功补偿容量匹配", ["rated_capacity_kvar"], ["q_mvar"], "投入容量应满足功率因数目标且不得引起电压越上限。", "GB 50052-2023"),
                _check("RC_HARM_001", "电容器谐波/串抗匹配", ["detuning_reactor_percent"], ["harmonic_voltage_distortion_percent"], "存在谐波时应配置合适电抗率或滤波装置。", "GB/T 14549-2024", "warning"),
            ],
            "metering_ct_pt": [
                _check("CT_I_001", "CT一次额定电流", ["rated_primary_a"], ["max_current_a"], "最大工作电流应在CT适用量程内。", "GB/T 20840.2-2014"),
                _check("CT_THERMAL_001", "CT热稳定", ["thermal_current_ka_1s"], ["ith_ka"], "安装点短时热电流不得超过CT热稳定能力。", "GB/T 20840.2-2014"),
                _check("CT_DYNAMIC_001", "CT动稳定", ["dynamic_current_ka"], ["ip_ka"], "短路峰值电流不得超过CT动稳定电流。", "GB/T 20840.2-2014"),
                _check("PT_BURDEN_001", "PT二次负荷", ["rated_secondary_burden_va"], ["secondary_burden_va"], "二次负荷不得超过额定二次负荷，精度等级应满足计量/保护用途。", "GB/T 20840.3-2013"),
            ],
            "surge_arrester": [
                _check("SA_UC_001", "避雷器持续运行电压", ["continuous_operating_voltage_kv"], ["max_phase_voltage_kv"], "系统最高相电压不得超过避雷器持续运行电压。", "GB/T 11032-2020"),
                _check("SA_RES_001", "避雷器残压与绝缘配合", ["residual_voltage_kv", "protected_equipment_bil_kv"], [], "避雷器残压应低于被保护设备绝缘耐受水平并保留配合裕度。", "GB/T 11032-2020"),
                _check("SA_DIS_001", "避雷器标称放电电流", ["nominal_discharge_current_ka"], [], "标称放电电流等级应匹配线路雷电活动和设备重要性。", "GB/T 11032-2020", "warning"),
            ],
            "load": [
                _check("LOAD_PQ_001", "负荷功率因数", ["p_mw", "q_mvar"], [], "功率因数应满足供配电设计和无功补偿目标。", "GB 50052-2023", "warning"),
                _check("LOAD_PROFILE_001", "负荷时序曲线", ["profile_id"], [], "规划年、最大负荷、最小负荷场景应绑定典型负荷曲线。", "DL/T 5729-2023", "warning"),
            ],
            "pv_inverter": [
                _check("PV_VRISE_001", "光伏接入电压升高", ["rated_power_kw"], ["voltage_rise_percent"], "PCC电压升高不得超过接入约束。", "NB/T 10994-2022"),
                _check("PV_HOST_001", "光伏渗透率", ["rated_power_kw", "connected_transformer_capacity_kva"], [], "光伏容量占变压器/馈线容量比例应满足工程设定限值。", "NB/T 10994-2022"),
                _check("PV_Q_001", "逆变器无功能力", ["sn_mva", "rated_power_kw", "power_factor_range"], ["q_mvar"], "逆变器应具备接入点要求的功率因数或Volt/Var能力。", "GB/T 19964-2012"),
                _check("PV_PQ_001", "并网电能质量", ["harmonic_current_percent", "anti_islanding"], ["thd_percent"], "谐波和孤岛保护应满足并网要求。", "GB/T 14549-2024"),
            ],
            "wind_turbine": [
                _check("WT_Q_001", "风机无功能力", ["rated_power_kw", "power_factor_range"], ["q_mvar"], "风机并网点功率因数或无功调节能力应满足要求。", "NB/T 10994-2022"),
                _check("WT_PQ_001", "风机电能质量", ["flicker_limit", "harmonic_current_percent"], ["flicker_plt", "thd_percent"], "闪变、谐波应满足电能质量要求。", "GB/T 12326-2023 / GB/T 14549-2024"),
            ],
            "storage": [
                _check("ES_P_001", "储能PCS功率", ["rated_charge_discharge_power_kw"], ["p_mw"], "充放电功率不得超过PCS额定功率。", "GB/T 34131-2023 / GB/T 36558-2023"),
                _check("ES_SOC_001", "储能SOC范围", ["soc_range_percent"], ["soc_percent"], "SOC应在允许运行范围内并保留备用容量。", "GB/T 36558-2023 / GB/T 36276-2023"),
                _check("ES_Q_001", "储能无功能力", ["sn_mva", "rated_charge_discharge_power_kw"], ["q_mvar"], "储能PCS视在功率应覆盖有功和无功组合。", "GB/T 34131-2023 / GB/T 36558-2023"),
            ],
            "ev_charger": [
                _check("EV_LOAD_001", "充电桩容量接入", ["rated_power_kw", "simultaneity_factor"], ["p_mw"], "充电负荷叠加后线路和变压器不得越限。", "GB/T 18487.1-2023"),
                _check("EV_PQ_001", "充电设备电能质量", ["power_factor", "harmonic_current_percent"], ["thd_percent"], "功率因数和谐波电流应满足电能质量要求。", "GB/T 14549-2024 / GB/T 18487.1-2023"),
            ],
        },
        "equipment_library_mapping": {
            "transformers.oil_immersed": ["transformer_2w", "TR2_LOAD_001", "TR2_SC_PARAM_001", "TR2_INS_001", "TR2_TEMP_001"],
            "transformers.dry_type": ["transformer_2w", "TR2_LOAD_001", "TR2_SC_PARAM_001", "TR2_INS_001", "TR2_TEMP_001"],
            "transformers.box_substation": ["box_substation", "BOX_LOAD_001", "BOX_SC_001", "BOX_IP_001"],
            "transformers.main_transformer_35kv": ["transformer_2w", "TR2_LOAD_001", "TR2_SC_PARAM_001", "TR2_THERMAL_001"],
            "transformers.main_transformer_110kv": ["transformer_2w", "TR2_LOAD_001", "TR2_SC_PARAM_001", "TR2_THERMAL_001"],
            "transformers.trafo3w_110kv": ["transformer_3w", "TR3_LOAD_001", "TR3_SC_PARAM_001"],
            "cables.mv_10kv": ["line_cable", "CAB_LOAD_001", "CAB_THERMAL_001", "CAB_VDROP_001", "CAB_ZERO_001"],
            "cables.mv_35kv": ["line_cable", "CAB_LOAD_001", "CAB_THERMAL_001", "CAB_VDROP_001", "CAB_ZERO_001"],
            "cables.lv_04kv": ["line_cable", "CAB_LOAD_001", "CAB_THERMAL_001", "CAB_VDROP_001"],
            "cables.hv_110kv": ["line_cable", "CAB_LOAD_001", "CAB_THERMAL_001", "CAB_ZERO_001"],
            "overhead_lines.mv_10kv_insulated": ["line_overhead", "OHL_LOAD_001", "OHL_THERMAL_001", "OHL_VDROP_001"],
            "overhead_lines.lv_04kv_insulated": ["line_overhead", "OHL_LOAD_001", "OHL_THERMAL_001", "OHL_VDROP_001"],
            "overhead_lines.bare_conductor": ["line_overhead", "OHL_LOAD_001", "OHL_THERMAL_001", "OHL_VDROP_001", "OHL_MECH_001"],
            "switchgear.switchgear_cabinet": ["switchgear_cabinet", "SWG_V_001", "SWG_I_001", "SWG_BREAK_001", "SWG_MAKE_001", "SWG_THERMAL_001"],
            "switchgear.circuit_breaker_mv": ["switch_breaker", "CB_I_001", "CB_BREAK_001", "CB_MAKE_001", "CB_THERMAL_001"],
            "switchgear.load_switch": ["load_switch", "LS_I_001", "LS_MAKE_001", "LS_THERMAL_001"],
            "switchgear.fuse_mv": ["fuse", "FUSE_BREAK_001", "FUSE_SELECT_001", "FUSE_SENS_001"],
            "switchgear.circuit_breaker_lv": ["circuit_breaker_lv", "LVCB_I_001", "LVCB_BREAK_001", "LVCB_SELECT_001"],
            "switchgear.recloser": ["recloser", "REC_BREAK_001", "REC_SEQ_001"],
            "switchgear.sectionalizer": ["sectionalizer", "SEC_MAKE_001", "SEC_COORD_001"],
            "reactive_compensation.capacitor_mv": ["reactive_compensation", "RC_V_001", "RC_Q_001", "RC_HARM_001"],
            "reactive_compensation.capacitor_lv": ["reactive_compensation", "RC_V_001", "RC_Q_001", "RC_HARM_001"],
            "reactive_compensation.svg": ["reactive_compensation", "RC_V_001", "RC_Q_001"],
            "instrument_transformers.ct_mv": ["metering_ct_pt", "CT_I_001", "CT_THERMAL_001", "CT_DYNAMIC_001"],
            "instrument_transformers.ct_lv": ["metering_ct_pt", "CT_I_001"],
            "instrument_transformers.pt_mv": ["metering_ct_pt", "PT_BURDEN_001"],
            "surge_arresters.arrester_mv": ["surge_arrester", "SA_UC_001", "SA_RES_001", "SA_DIS_001"],
            "surge_arresters.arrester_lv": ["surge_arrester", "SA_UC_001", "SA_RES_001"],
            "photovoltaic.string_inverter": ["pv_inverter", "PV_VRISE_001", "PV_HOST_001", "PV_Q_001", "PV_PQ_001"],
            "photovoltaic.central_inverter": ["pv_inverter", "PV_VRISE_001", "PV_HOST_001", "PV_Q_001", "PV_PQ_001"],
            "wind_turbine.small_wind": ["wind_turbine", "WT_Q_001", "WT_PQ_001"],
            "wind_turbine.medium_wind": ["wind_turbine", "WT_Q_001", "WT_PQ_001"],
            "energy_storage.lfp_battery": ["storage", "ES_P_001", "ES_SOC_001"],
            "energy_storage.lead_carbon_battery": ["storage", "ES_P_001", "ES_SOC_001"],
            "energy_storage.pcs": ["storage", "ES_P_001", "ES_Q_001"],
            "ev_charger.ac_slow": ["ev_charger", "EV_LOAD_001", "EV_PQ_001"],
            "ev_charger.dc_fast": ["ev_charger", "EV_LOAD_001", "EV_PQ_001"],
            "ev_charger.dc_superfast": ["ev_charger", "EV_LOAD_001", "EV_PQ_001"],
        },
    }
